trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository

steps:

# ==========================================
# 1. Check Java and Maven
# ==========================================

- script: |
    java -version
    javac -version
    mvn -version
  displayName: 'Check Java and Maven'


# ==========================================
# 2. Maven Build + Unit Tests
# ==========================================

- task: Maven@4
  displayName: 'Maven Build and Test'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    options: '-DskipTests=false'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false


# ==========================================
# 3. Prepare SonarQube
# ==========================================

- task: SonarQubePrepare@7
  displayName: 'Prepare SonarQube Analysis'
  inputs:
    SonarQube: 'sonarqube-connection'
    scannerMode: 'other'
    extraProperties: |
      sonar.projectKey=demo-app
      sonar.projectName=demo-app
      sonar.java.binaries=target/classes


# ==========================================
# 4. Run SonarQube Analysis
# ==========================================

- task: Maven@4
  displayName: 'SonarQube Code Analysis'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'sonar:sonar'
    options: '-DskipTests=false'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false


# ==========================================
# 5. Publish SonarQube Quality Gate
# ==========================================

- task: SonarQubePublish@7
  displayName: 'Publish SonarQube Results'
  inputs:
    pollingTimeoutSec: '300'


# ==========================================
# 6. Publish Application JAR
# ==========================================

- task: PublishPipelineArtifact@1
  displayName: 'Publish Application JAR'
  inputs:
    targetPath: '$(Build.SourcesDirectory)/target'
    artifact: 'application'
    publishLocation: 'pipeline'
