trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository

steps:

# ==========================================
# 1. Check Java
# ==========================================

- script: |
    java -version
    javac -version
    mvn -version
  displayName: 'Check Java and Maven'


# ==========================================
# 2. Maven Build
# ==========================================

- task: Maven@4
  displayName: 'Maven Build'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    options: '-DskipTests=false'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false


# ==========================================
# 3. Publish JAR
# ==========================================

- task: PublishPipelineArtifact@1
  displayName: 'Publish Application JAR'
  inputs:
    targetPath: '$(Build.SourcesDirectory)/target'
    artifact: 'application'
    publishLocation: 'pipeline'
